# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/chantico-local-path-data
        containerPath: /opt/local-path-provisioner
    extraPortMappings:
    - containerPort: 31161
      hostPort: 31161
      protocol: UDP
    - containerPort: 31162
      hostPort: 31162
      protocol: UDP
