# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ./.chantico-persistent-volume
      containerPath: /data/chantico-persistent-volume
    extraPortMappings:
    - hostPort: 31161 # chantico-snmp-mock
      containerPort: 31161
      protocol: UDP
    - hostPort: 19116 # chantico-snmp
      containerPort: 9116
    - hostPort: 18888 # filebrowser
      containerPort: 30000
    - hostPort: 19090 # prometheus
      containerPort: 30001
