---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources
  - measurementdevices
  - physicalmeasurements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources/finalizers
  verbs:
  - update
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources/status
  - measurementdevices/status
  - physicalmeasurements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - measurementdevices/finalizers
  - physicalmeasurements/finalizers
  verbs:
  - create
  - patch
  - update
