---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources
  - physicalmeasurements
  - snmpdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources/finalizers
  verbs:
  - update
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - datacenterresources/status
  - physicalmeasurements/status
  - snmpdevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - physicalmeasurements/finalizers
  - snmpdevices/finalizers
  verbs:
  - create
  - patch
  - update
