# permissions for end users to edit snmpdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: snmpdevice-editor-role
rules:
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - snmpdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chantico.ci.tno.nl
  resources:
  - snmpdevices/status
  verbs:
  - get
