apiVersion: chantico.ci.tno.nl/v1alpha1
kind: SNMPDevice
metadata:
  name: tno2
  namespace: chantico
  labels:
    app.kubernetes.io/name: chantico
spec:
  auth:
    community: public
    version: 2
  walks:
    - tnoPduEnergyValue
    - tnoPduPowerValue