apiVersion: chantico.ci.tno.nl/v1alpha1
kind: MeasurementDevice
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: tno
  namespace: chantico
spec:
  auth:
    community: public
    version: 2
  walks:
    - tnoPduPowerValue
