# apiVersion: chantico.ci.tno.nl/v1alpha1
# kind: SNMPDevice
# metadata:
#   labels:
#     app.kubernetes.io/name: chantico
#     app.kubernetes.io/managed-by: kustomize
#   name: tno
#   namespace: chantico
# spec:
#   auth:
#     community: public
#     version: 2
#   walks:
#     - tnoPduEnergyValue
#     # - tnoPduPowerValue
# ---
# apiVersion: chantico.ci.tno.nl/v1alpha1
# kind: SNMPDevice
# metadata:
#   labels:
#     app.kubernetes.io/name: chantico
#     app.kubernetes.io/managed-by: kustomize
#   name: tno1
#   namespace: chantico
# spec:
#   auth:
#     community: public
#     version: 2
#   walks:
#     - tnoPduEnergyValue
#     - tnoPduPowerValue
# ---
apiVersion: chantico.ci.tno.nl/v1alpha1
kind: SNMPDevice
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: tno
  namespace: chantico
spec:
  auth:
    community: public
    version: 2
  walks:
    - tnoPduPowerValue
