//go:build !ignore_autogenerated

/*
Copyright 2025-2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCenterResource) DeepCopyInto(out *DataCenterResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCenterResource.
func (in *DataCenterResource) DeepCopy() *DataCenterResource {
	if in == nil {
		return nil
	}
	out := new(DataCenterResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataCenterResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCenterResourceList) DeepCopyInto(out *DataCenterResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataCenterResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCenterResourceList.
func (in *DataCenterResourceList) DeepCopy() *DataCenterResourceList {
	if in == nil {
		return nil
	}
	out := new(DataCenterResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataCenterResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCenterResourceSpec) DeepCopyInto(out *DataCenterResourceSpec) {
	*out = *in
	if in.PhysicalMeasurements != nil {
		in, out := &in.PhysicalMeasurements, &out.PhysicalMeasurements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parents != nil {
		in, out := &in.Parents, &out.Parents
		*out = make([]ParentRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCenterResourceSpec.
func (in *DataCenterResourceSpec) DeepCopy() *DataCenterResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataCenterResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCenterResourceStatus) DeepCopyInto(out *DataCenterResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCenterResourceStatus.
func (in *DataCenterResourceStatus) DeepCopy() *DataCenterResourceStatus {
	if in == nil {
		return nil
	}
	out := new(DataCenterResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasurementDevice) DeepCopyInto(out *MeasurementDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasurementDevice.
func (in *MeasurementDevice) DeepCopy() *MeasurementDevice {
	if in == nil {
		return nil
	}
	out := new(MeasurementDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeasurementDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasurementDeviceList) DeepCopyInto(out *MeasurementDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeasurementDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasurementDeviceList.
func (in *MeasurementDeviceList) DeepCopy() *MeasurementDeviceList {
	if in == nil {
		return nil
	}
	out := new(MeasurementDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeasurementDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasurementDeviceSpec) DeepCopyInto(out *MeasurementDeviceSpec) {
	*out = *in
	if in.Walks != nil {
		in, out := &in.Walks, &out.Walks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasurementDeviceSpec.
func (in *MeasurementDeviceSpec) DeepCopy() *MeasurementDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MeasurementDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasurementDeviceStatus) DeepCopyInto(out *MeasurementDeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasurementDeviceStatus.
func (in *MeasurementDeviceStatus) DeepCopy() *MeasurementDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MeasurementDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentRef) DeepCopyInto(out *ParentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentRef.
func (in *ParentRef) DeepCopy() *ParentRef {
	if in == nil {
		return nil
	}
	out := new(ParentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalMeasurement) DeepCopyInto(out *PhysicalMeasurement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalMeasurement.
func (in *PhysicalMeasurement) DeepCopy() *PhysicalMeasurement {
	if in == nil {
		return nil
	}
	out := new(PhysicalMeasurement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalMeasurement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalMeasurementList) DeepCopyInto(out *PhysicalMeasurementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PhysicalMeasurement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalMeasurementList.
func (in *PhysicalMeasurementList) DeepCopy() *PhysicalMeasurementList {
	if in == nil {
		return nil
	}
	out := new(PhysicalMeasurementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalMeasurementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalMeasurementSpec) DeepCopyInto(out *PhysicalMeasurementSpec) {
	*out = *in
	if in.ResourceIds != nil {
		in, out := &in.ResourceIds, &out.ResourceIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalMeasurementSpec.
func (in *PhysicalMeasurementSpec) DeepCopy() *PhysicalMeasurementSpec {
	if in == nil {
		return nil
	}
	out := new(PhysicalMeasurementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalMeasurementStatus) DeepCopyInto(out *PhysicalMeasurementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalMeasurementStatus.
func (in *PhysicalMeasurementStatus) DeepCopy() *PhysicalMeasurementStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalMeasurementStatus)
	in.DeepCopyInto(out)
	return out
}
