baseURL = 'https://chantico-300062.ci.tno.nl/'
languageCode = 'en-us'
title = 'Chantico'
theme = 'hugo-theme-relearn'
contentDir = '..'
ignoreFiles = ['hugo/*']
copyright = 'Copyright 2025-2026 TNO. Chantico is licensed under the <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>. Published documentation is available under <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC-BY-SA 4.0</a>.'

[markup]
  [markup.highlight]
    noClasses = false   # generates <span class="keyword"> for styling
    style = "monokai"   # or any preferred theme

[params]
disableInlineCopyToClipBoard = true
themeVariant = ['relearn-dark', 'relearn-light']

[params.sidebar]
  autoCollapsed = false

[params.author]
  name = 'TNO'

[params.assets]
  disableFingerprinting = false

[params.logo]
  direction = 'column'
  src = '/assets/logo/chantico.png'
