apiVersion: v1
kind: Service
metadata:
  name: chantico-snmp-mock-2
  namespace: chantico
spec:
  selector:
    app: chantico-snmp-mock-2
  ports:
  - protocol: UDP
    port: 1161
    targetPort: 1161
    nodePort: 31162
  type: NodePort
