apiVersion: v1
kind: Service
metadata:
  name: chantico-snmp-mock
spec:
  selector:
    app: chantico-snmp-mock
  ports:
  - protocol: UDP
    port: 1161
    targetPort: 1161
    nodePort: 31161     # NodePort (must be between 30000–32767)
  type: NodePort
