apiVersion: apps/v1
kind: Deployment
metadata:
  name: chantico-snmp-mock
  labels:
    app: chantico-snmp-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantico-snmp-mock
  template:
    metadata:
      labels:
        app: chantico-snmp-mock
    spec:
      containers:
      - name: chantico-snmp-mock
        image: chantico-snmp-mock:latest
        imagePullPolicy: Never
        args: ["1000"]  # Port(s) to listen on, matches your app’s CLI argument
        ports:
        - containerPort: 1161
          protocol: UDP
