apiVersion: v1
kind: Service
metadata:
  name: chantico-vm-attribution-mock
spec:
  selector:
    app: chantico-vm-attribution-mock
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30909  # NodePort (must be between 30000–32767)
  type: NodePort