{
 "title": "Datacenter overview",
 "tags": [ "chantico" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current energy per PDU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chantico_power_watts{type=\"pdu\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Total power (all PDUs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chantico_power_watts{type=\"pdu\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Scraping interval",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{interval=\"10s\", quantile=\"0.99\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "PDU power consumption over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "chantico_power_watts{type=\"pdu\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Baremetal power consumption over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "chantico_power_watts{type=\"baremetal\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}