@startuml

	top to bottom direction

	skinparam nodesep 90
	skinparam ranksep 120

	circle GridA #Red
	circle GridB #Red
	circle GeneratorA #Red
	circle GeneratorB #Red
	circle BatteryA #Red
	circle BatteryB #Red


	circle PowerFeedA #Red
	circle PowerFeedB #Red


	circle PDU1A #Blue
	circle PDU1B #Blue
	circle PDU2A #Blue
	circle PDU2B #Blue
	circle PDU3A #Blue
	circle PDU3B #Blue


	GridA -right[hidden]-> GeneratorA
	GeneratorA -right[hidden]-> BatteryA
	BatteryA -right[hidden]-> GridB
	GridB -right[hidden]-> GeneratorB
	GeneratorB -right[hidden]-> BatteryB


	PowerFeedA -right[hidden]-> PowerFeedB


	PDU1A -right[hidden]-> PDU1B
	PDU1B -right[hidden]-> PDU2A
	PDU2A -right[hidden]-> PDU2B
	PDU2B -right[hidden]-> PDU3A
	PDU3A -right[hidden]-> PDU3B


	GridA -down-> PowerFeedA
	GridB -down-> PowerFeedB
	BatteryA -down-> PowerFeedA
	BatteryB -down-> PowerFeedB
	GeneratorA -down-> PowerFeedA
	GeneratorB -down-> PowerFeedB


	PowerFeedA -down-> PDU1A
	PowerFeedB -down-> PDU1B
	PowerFeedA -down-> PDU2A
	PowerFeedB -down-> PDU2B
	PowerFeedA -down-> PDU3A
	PowerFeedB -down-> PDU3B


	circle Baremetal1 #Blue
	circle Baremetal2 #Green
	circle Baremetal3 #Blue
	circle Baremetal4 #Blue
	circle Baremetal5 #Blue
	circle Baremetal6 #Green
	circle Baremetal7 #Blue
	circle Baremetal8 #Green
	circle Baremetal9 #Green
	circle Baremetal10 #Green
	circle Baremetal11 #Green
	circle Baremetal12 #Green


	circle VM1 #Green
	circle VM2 #Green
	circle VM3 #Green
	circle VM4 #Blue
	circle VM5 #Blue
	circle VM6 #Blue
	circle VM7 #Green

	circle Kubernetes1 #Green
	circle Kubernetes2 #Blue

	circle Pod1 #Green
	circle Pod2 #Green
	circle Pod3 #Green

	Baremetal1 -right[hidden]-> Baremetal2
	Baremetal2 -right[hidden]-> Baremetal3
	Baremetal3 -right[hidden]-> Baremetal4
	Baremetal4 -right[hidden]-> Baremetal5
	Baremetal5 -right[hidden]-> Baremetal6
	Baremetal6 -right[hidden]-> Baremetal7
	Baremetal7 -right[hidden]-> Baremetal8
	Baremetal8 -right[hidden]-> Baremetal9
	Baremetal9 -right[hidden]-> Baremetal10
	Baremetal10 -right[hidden]-> Baremetal11
	Baremetal11 -right[hidden]-> Baremetal12


	VM1 -right[hidden]-> VM2
	VM2 -right[hidden]-> VM3
	VM3 -right[hidden]-> VM4
	VM4 -right[hidden]-> VM5
	VM5 -right[hidden]-> VM6
	VM6 -right[hidden]-> VM7


	Kubernetes1 -right[hidden]-> Kubernetes2


	Pod1 -right[hidden]-> Pod2
	Pod2 -right[hidden]-> Pod3


	PDU1A -down-> Baremetal1
	PDU1B -down-> Baremetal1
	PDU1A -down-> Baremetal2
	PDU1B -down-> Baremetal2
	PDU1A -down-> Baremetal3
	PDU1B -down-> Baremetal3
	PDU1A -down-> Baremetal4
	PDU1B -down-> Baremetal4
	PDU2A -down-> Baremetal5
	PDU2B -down-> Baremetal5
	PDU2A -down-> Baremetal6
	PDU2B -down-> Baremetal6
	PDU2A -down-> Baremetal7
	PDU2B -down-> Baremetal7
	PDU2A -down-> Baremetal8
	PDU2B -down-> Baremetal8
	PDU3A -down-> Baremetal9
	PDU3B -down-> Baremetal9
	PDU3A -down-> Baremetal10
	PDU3B -down-> Baremetal10
	PDU3A -down-> Baremetal11
	PDU3B -down-> Baremetal11
	PDU3A -down-> Baremetal12
	PDU3B -down-> Baremetal12



	Baremetal1 -down-> VM1
	Baremetal1 -down-> VM2
	Baremetal1 -down-> VM3
	Baremetal3 -down-> VM4
	Baremetal3 -down-> VM5
	Baremetal5 -down-> VM6
	Baremetal5 -down-> VM7


	VM4 -down-> Kubernetes1
	VM5 -down-> Kubernetes1
	VM6 -down-> Kubernetes1

	Baremetal4 -down-> Kubernetes2
	Baremetal7 -down-> Kubernetes2


	Kubernetes2 -down-> Pod1
	Kubernetes2 -down-> Pod2
	Kubernetes2 -down-> Pod3

@enduml
