@startuml
title: Use case 1

cloud Physical{
	rectangle PDU1 {
		portOut p11
		portOut p12
		portOut p13
	}

	rectangle PDU2 {
		portOut p21
		portOut p22
		portOut p23
	}
	rectangle Server
}


rectangle Baremetal

cloud chantico as "EDC / Chantico"{

	rectangle SNMPExporter
	rectangle Prometheus
}

p11 -down-> Server
p22 -down-> Server
Server -down-> Baremetal

PDU1 -right-> SNMPExporter
PDU2 -right-> SNMPExporter
Server -right-> SNMPExporter
SNMPExporter -right-> Prometheus

@enduml
