@startuml
title: Interaction with the Workflow Orchestrator / Engineer / Chantico

group initialize
	Engineer -[#green]-> Chantico: Install
	Chantico -[#green]-> Chantico: Initialize SNMP / Prometheus / default
end

group registerPDU
Engineer -[#green]-> Chantico: Upload MIB
Engineer -[#green]-> Chantico: Create SNMP yaml
Chantico -[#green]-> Chantico: Set-up SNMP
end

group createPDU1
WorkflowOrchestrator -> WorkflowOrchestrator: Get IP from PPAM
WorkflowOrchestrator -[#green]-> Chantico: ServiceId, IP
Chantico -[#green]-> Chantico: Start scrapping
Chantico -> WorkflowOrchestrator: 200 (OK), List outlets
end createPDU

group createPDU2
WorkflowOrchestrator -> WorkflowOrchestrator: Get IP from PPAM
WorkflowOrchestrator -[#green]-> Chantico: ServiceId, IP
Chantico -[#green]-> Chantico: Start scrapping
Chantico -> WorkflowOrchestrator: 200 (OK), List outlets
end createPDU

group createServer
WorkflowOrchestrator -> Chantico: ServiceId, List ResourceId
Chantico -[#orange]-> Chantico: Start aggregating
Chantico -> WorkflowOrchestrator: 200 (OK)
end createServer

group createBaremetal
WorkflowOrchestrator -> Chantico: ServiceId, ResourceId Server + Frequency
Chantico -> Chantico: Start aggregating
Chantico -> WorkflowOrchestrator: 200 (OK)
end createBaremetal
@enduml
