baseURL = 'https://chantico-project.github.io/chantico/'
locale = 'en-us'
title = 'Chantico'
theme = 'github.com/McShelby/hugo-theme-relearn'
copyright = 'Copyright 2025-2026 TNO. Chantico is licensed under the <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>. Published documentation is available under <a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC-BY 4.0</a>.'

[security]
allowContent = ['.*']

[markup]
  [markup.highlight]
    noClasses = false   # generates <span class="keyword"> for styling
    style = "monokai"   # or any preferred theme

[params]
disableInlineCopyToClipBoard = true
themeVariant = ['relearn-dark', 'relearn-light']

[params.sidebar]
  autoCollapsed = false

[params.author]
  name = 'TNO'

[params.assets]
  disableFingerprinting = false

[params.logo]
  direction = 'column'
  src = 'logo/chantico.png'