{{- if and .Values.controller.include .Values.controller.image.repository }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chantico-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chantico-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          env:
            - name: CHANTICOVOLUMELOCATIONENV
              value: "/data"
            - name: CHANTICOVOLUMECLAIMENV
              value: {{ .Values.persistentVolumeClaimName }}
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: chantico-volume
              mountPath: /data
      volumes:
        - name: chantico-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaimName }}
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      serviceAccountName: chantico-controller-manager
      terminationGracePeriodSeconds: 10
{{- end }}