{{- if .Values.pvc.include }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaimName }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: chantico-persistent-volume
  storageClassName: manual
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chantico-persistent-volume
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  storageClassName: manual
  hostPath:
    path: /data/chantico-persistent-volume
  accessModes:
  - ReadWriteOnce
{{- end }}