{{- if .Values.pvc.include }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaimName }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: fixed-pv
  storageClassName: manual
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fixed-pv 
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  storageClassName: manual
  hostPath:
    path: /data/fixed-pv
  accessModes:
  - ReadWriteOnce
{{- end }}