{{- if .Values.pvc.include }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaimName }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{- end }}