apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chantico
  name: chantico-snmp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantico-snmp
  template:
    metadata:
      labels:
        app: chantico-snmp
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: ricardbejarano/snmp_exporter:0.26.0
        name: snmp
        volumeMounts:
        - mountPath: "/snmp.yml"
          name: chantico-volume-mount
          subPath: "snmp/yml/snmp.yml"
        ports:
        - containerPort: 9116
      initContainers:
      - image: busybox
        name: structure-initialization
        command: ["/bin/sh"]
        args:
          - -c
          - |
            mkdir -p /tmp/chantico-volume-mount/snmp/mibs;
            mkdir -p /tmp/chantico-volume-mount/snmp/generators;
            mkdir -p /tmp/chantico-volume-mount/snmp/yml;
            if [ ! -f /tmp/chantico-volume-mount/snmp/yml/snmp.yml ]; then
              touch /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "auths:" > /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "  default:" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    community: public" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    security_level: noAuthNoPriv" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    username: guest" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    auth_protocol: MD5" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    priv_protocol: DES" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    version: 3" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "modules:" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "  init:" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    walk: []" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
              echo "    metrics: []" >> /tmp/chantico-volume-mount/snmp/yml/snmp.yml;
            fi
            chmod -R 1777 /tmp/chantico-volume-mount/snmp
        volumeMounts:
        - mountPath: "/tmp/chantico-volume-mount"
          name: chantico-volume-mount
      volumes:
      - name: chantico-volume-mount
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaimName }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chantico-snmp
spec:
  selector:
    app: chantico-snmp
  ports:
    - protocol: TCP
      port: 9116
      targetPort: 9116
