name: Documentation

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  GO_VERSION: "1.25"

jobs:
  # Documentation build
  docs:
    runs-on: ubuntu-latest
    outputs:
      clean_ref: ${{ steps.clean_name.outputs.clean_ref }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Sanitize ref to use in artifact names
        id: clean_name
        run: |
          # Use sed to replace all '/' with '-'
          CLEAN_REF=$(echo "${{ github.ref }}" | sed 's/\//-/g')
          echo "clean_ref=${CLEAN_REF}" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate docs
        run: |
          REL_LINK_STYLE=index
          if [[ "${{ inputs.ref }}" == "main" ]]; then
            REL_LINK_STYLE=directory
          fi
          export REL_LINK_STYLE
          make docs-build

      - uses: actions/upload-artifact@v7
        with:
          name: docs-${{ steps.clean_name.outputs.clean_ref }}
          path: docs

  # Documentation preview artifact
  preview:
    if: inputs.ref != 'refs/heads/main' && !startsWith(inputs.ref, 'refs/tags/v')
    needs: docs
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:debian-exts
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: docs-${{ needs.docs.outputs.clean_ref }}
          path: docs

      - name: Build preview
        run: |
          cd docs
          hugo --baseURL="/" --config "hugo.toml,hugo.preview.toml"

      - name: Upload preview artifact
        uses: actions/upload-artifact@v7
        with:
          name: hugo-preview-${{ needs.docs.outputs.clean_ref }}
          path: docs/public

  # Check links in documentation preview
  docs-check-links:
    if: inputs.ref != 'refs/heads/main' && !startsWith(inputs.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [docs, preview]
    continue-on-error: true
    env:
      DOCS_PORT: 8000
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: hugo-preview-${{ needs.docs.outputs.clean_ref }}

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Start local server
        run: |
          cat <<'EOF' > server.go
          package main
          import (
            "log"
            "net/http"
            "os"
          )
          func main() {
            port := os.Getenv("DOCS_PORT")
            log.Printf("Serving on :%s", port)
            log.Fatal(http.ListenAndServe(":" + port, http.FileServer(http.Dir("."))))
          }
          EOF

          go run server.go &
          echo $! > server.pid

      - name: Run link checker
        run: |
          make docs-test

      - name: Stop server
        if: always()
        run: kill $(cat server.pid)

  # Deployment of documentation to GitHub Pages
  pages:
    if: inputs.ref == 'refs/heads/main' || startsWith(inputs.ref, 'refs/tags/v')
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    container:
      image: hugomods/hugo:debian-exts

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/download-artifact@v8
        with:
          name: docs-${{ needs.docs.outputs.clean_ref }}
          path: docs

      - name: Build site
        run: |
          cd docs
          hugo --baseURL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      - uses: actions/upload-pages-artifact@v5
        with:
          name: pages-${{ needs.docs.outputs.clean_ref }}
          path: docs/public

      - id: deploy
        uses: actions/deploy-pages@v5
        with:
          artifact_name: pages-${{ needs.docs.outputs.clean_ref }}
