name: Documentation

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  GO_VERSION: "1.26"

jobs:
  # Documentation build
  docs:
    runs-on: ubuntu-latest
    outputs:
      clean_ref: ${{ steps.clean_name.outputs.clean_ref }}
    env:
      DOCS_PORT: 1313
      DOCS_VERBOSE: true
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Sanitize ref to use in artifact names
        id: clean_name
        run: |
          # Use sed to replace all '/' with '-'
          CLEAN_REF=$(echo "${{ github.ref }}" | sed 's/\//-/g')
          echo "clean_ref=${CLEAN_REF}" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build and run documentation
        run: |
          make docs-serve &

          echo "Waiting for Hugo server on port ${{ env.DOCS_PORT }}..."
          TIMEOUT=180
          ELAPSED=0
          
          while ! curl -s --head http://localhost:${{ env.DOCS_PORT }} > /dev/null; do
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "Error: Hugo server failed to start within $TIMEOUT seconds."
              exit 1
            fi
            sleep 1
            ELAPSED=$((ELAPSED + 1))
          done
          
          echo "Hugo server is up and running!"

      - name: Run tests against local server
        run: |
          make docs-test

      - uses: actions/upload-artifact@v7
        with:
          name: docs-${{ steps.clean_name.outputs.clean_ref }}
          path: docs/public

  # Deployment of documentation to GitHub Pages
  pages:
    if: inputs.ref == 'refs/heads/main' || startsWith(inputs.ref, 'refs/tags/v')
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: docs-${{ needs.docs.outputs.clean_ref }}
          path: public-html

      - uses: actions/upload-pages-artifact@v5
        with:
          name: pages-${{ needs.docs.outputs.clean_ref }}
          path: public-html

      - id: deploy
        uses: actions/deploy-pages@v5
        with:
          artifact_name: pages-${{ needs.docs.outputs.clean_ref }}
