name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string


permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  # GoReleaser
  release:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.repository == 'chantico-project/chantico'
    concurrency:
      group: ${{ github.workflow }}-v${{ inputs.version }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
        with:
          ref: refs/tags/v${{ inputs.version }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.1
        with:
          version: latest
          args: release --config .goreleaser.github.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_RELEASE_TOKEN }}
