name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string


permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  # GoReleaser
  release:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.repository == 'chantico-project/chantico'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
        with:
          ref: v${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.1
        with:
          version: latest
          args: release --config .goreleaser.github.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_RELEASE_TOKEN }}

  # Helm release
  helm:
    runs-on: ubuntu-latest
    if: github.repository == 'chantico-project/chantico'

    steps:
      - uses: actions/checkout@v6
        with:
          ref: v${{ github.event.inputs.version }}

      - name: Setup Helm
        uses: azure/setup-helm@v5

      - name: Package and push chart
        run: |
          make sync-deployment-crds
          echo "${{ secrets.BOT_RELEASE_TOKEN }}" | helm registry login ghcr.io -u chantico-bot --password-stdin
          VERSION=${{ github.event.inputs.version }}
          helm package config/deployment/ --version $VERSION --app-version v$VERSION
          helm push chantico-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
